# BoardConfig.mk — Google Pixel 7 (panther)
# ninjamagicOS device configuration

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a76

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_VARIANT := cortex-a55

# SoC
TARGET_BOARD_PLATFORM := gs201
TARGET_SOC := tensor_gs201

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := panther
TARGET_NO_BOOTLOADER := false

# Kernel
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_IMAGE_NAME := Image.lz4
TARGET_KERNEL_SOURCE := kernel/google/gs201
TARGET_KERNEL_CONFIG := ninjamagic_panther_defconfig
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_MOVE_GSI_AVB_KEYS_TO_VENDOR_BOOT := true

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864       # 64MB
BOARD_DTBOIMG_PARTITION_SIZE := 25165824         # 24MB
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := google_dynamic_partitions
BOARD_GOOGLE_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext product vendor vendor_dlkm system_dlkm
BOARD_GOOGLE_DYNAMIC_PARTITIONS_SIZE := 9122611200

# Filesystem
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs

# Display
TARGET_SCREEN_DENSITY := 420
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2400

# GPU
BOARD_GPU_TYPE := mali-g710

# NPU / ML Accelerator
BOARD_HAS_NPU := true
BOARD_NPU_TYPE := tensor_tpu

# Radio / Modem
BOARD_MODEM_TYPE := exynos_5300
ENABLE_VENDOR_RIL_SERVICE := true

# Security
BOARD_AVB_ENABLE := true
BOARD_USES_TRUSTY_TEE := true
BOARD_HAS_TITAN_M2 := true

# MSI (ninjamagicOS cognitive runtime)
BOARD_MSI_KERNEL_MODULE := true
BOARD_MSI_LANES_MAX := 1024
BOARD_MSI_EVENTS_MAX_TOPICS := 65536
BOARD_MSI_ASSOC_NPU_ACCEL := true

# SELinux
BOARD_SEPOLICY_DIRS += device/google/panther/sepolicy

# WiFi
BOARD_WLAN_DEVICE := bcmdhd
BOARD_WPA_SUPPLICANT_DRIVER := NL80211

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/google/panther/bluetooth
