//! SP Lowering — transforms AST into MSI runtime calls
//!
//! Converts parsed SP programs into Rust source code that uses
//! the msi-runtime crate. This is the bridge between the SP
//! language and the MSI kernel module.
//!
//! Lowering rules (from SingularisPrime/substrate/lowering.md):
//!   domain D { grant events "x/" ; sealed }
//!     → substrate.domain("D").grant(Grant::Events("x/")).seal().build()
//!
//!   lane main in D { priority high; ... }
//!     → Lane::spawn(fd, domain.id(), "main", LanePolicy::new(High, ...))
//!
//!   event.publish(topic, payload)
//!     → event_bus.emit(domain_id, topic, payload)
//!
//!   assoc.put(space, key, value)
//!     → store.put(key, AssocValue::from_str(value))

use crate::ast::*;
use crate::error::{SpError, Result};

/// Generated Rust code from lowering.
#[derive(Debug, Clone)]
pub struct LoweredProgram {
    /// Rust source code for the lowered program.
    pub rust_source: String,
    /// Domain names referenced.
    pub domains: Vec<String>,
    /// Lane names referenced.
    pub lanes: Vec<String>,
}

/// Lower an SP program AST to Rust source using msi-runtime.
pub fn lower(program: &Program) -> Result<LoweredProgram> {
    let mut out = String::new();
    let mut domain_names = Vec::new();
    let mut lane_names = Vec::new();

    // File header
    out.push_str("// Auto-generated by spc (Shinobi.Substrate Compiler)\n");
    out.push_str("// Do not edit — regenerate from .sp source\n\n");
    out.push_str("use msi::{Substrate, Grant, Perms};\n");
    out.push_str("use msi::lane::{Lane, LanePolicy, Priority, EnergyBudget, Affinity};\n");
    out.push_str("use msi::event::QoS;\n");
    out.push_str("use msi::assoc::{AssocStore, AssocValue, AssocQuery};\n");
    out.push_str("use std::time::Duration;\n\n");

    // Main function
    out.push_str("fn main() {\n");
    out.push_str("    env_logger::init();\n");
    out.push_str("    let substrate = Substrate::connect().expect(\"MSI substrate\");\n");
    out.push_str("    let event_bus = substrate.event_bus();\n\n");

    // Lower domains
    for domain in &program.domains {
        domain_names.push(domain.name.clone());
        lower_domain(&mut out, domain)?;
    }

    // Lower lanes
    for lane in &program.lanes {
        lane_names.push(lane.name.clone());
        lower_lane(&mut out, lane)?;
    }

    out.push_str("}\n");

    Ok(LoweredProgram {
        rust_source: out,
        domains: domain_names,
        lanes: lane_names,
    })
}

fn lower_domain(out: &mut String, domain: &DomainDecl) -> Result<()> {
    let var = to_snake(&domain.name);
    out.push_str(&format!("    // Domain: {}\n", domain.name));
    out.push_str(&format!("    let {var} = substrate.domain(\"{}\")\n", domain.name));

    for grant in &domain.grants {
        match grant {
            GrantDecl::Events(prefix) => {
                out.push_str(&format!("        .grant(Grant::Events(\"{prefix}\".into()))\n"));
            }
            GrantDecl::State(name, perm) => {
                let p = match perm {
                    PermMode::Read => "Perms::Read",
                    PermMode::ReadWrite => "Perms::ReadWrite",
                };
                out.push_str(&format!("        .grant(Grant::State(\"{name}\".into(), {p}))\n"));
            }
            GrantDecl::Assoc(space, perm) => {
                let p = match perm {
                    PermMode::Read => "Perms::Read",
                    PermMode::ReadWrite => "Perms::ReadWrite",
                };
                out.push_str(&format!("        .grant(Grant::Assoc(\"{space}\".into(), {p}))\n"));
            }
            GrantDecl::Clock => {
                out.push_str("        .grant(Grant::Clock)\n");
            }
            GrantDecl::Accel(which) => {
                out.push_str(&format!("        .grant(Grant::Accel(\"{which}\".into()))\n"));
            }
        }
    }

    if domain.sealed {
        out.push_str("        .seal()\n");
    }

    out.push_str(&format!("        .build().expect(\"domain {}\");\n\n", domain.name));
    Ok(())
}

fn lower_lane(out: &mut String, lane: &LaneDecl) -> Result<()> {
    let domain_var = to_snake(&lane.domain);

    out.push_str(&format!("    // Lane: {} in {}\n", lane.name, lane.domain));

    // Lower policy
    let priority = match lane.policy.priority {
        Some(PriorityLevel::Low) => "Priority::Low",
        Some(PriorityLevel::Normal) => "Priority::Normal",
        Some(PriorityLevel::High) => "Priority::High",
        Some(PriorityLevel::Realtime) => "Priority::Realtime",
        None => "Priority::Normal",
    };

    let energy = match lane.policy.energy {
        Some(EnergyLevel::Low) => "EnergyBudget::Low",
        Some(EnergyLevel::Balanced) => "EnergyBudget::Balanced",
        Some(EnergyLevel::Unbounded) => "EnergyBudget::Unbounded",
        None => "EnergyBudget::Balanced",
    };

    let affinity = match lane.policy.affinity {
        Some(AffinityTarget::Any) => "Affinity::Any",
        Some(AffinityTarget::Little) => "Affinity::Little",
        Some(AffinityTarget::Big) => "Affinity::Big",
        Some(AffinityTarget::Npu) => "Affinity::Npu",
        Some(AffinityTarget::Gpu) => "Affinity::Gpu",
        Some(AffinityTarget::Dsp) => "Affinity::Dsp",
        None => "Affinity::Any",
    };

    out.push_str(&format!(
        "    let _lane_{} = Lane::spawn(\n        substrate.fd(),\n        {domain_var}.id(),\n        \"{}\",\n        LanePolicy::new({priority}, {energy}, {affinity}),\n    ).expect(\"lane {}\");\n\n",
        to_snake(&lane.name), lane.name, lane.name
    ));

    // Lower body statements
    out.push_str("    // Lane body\n");
    for stmt in &lane.body {
        lower_stmt(out, stmt, &lane.domain, 1)?;
    }
    out.push('\n');

    Ok(())
}

fn lower_stmt(out: &mut String, stmt: &Stmt, domain: &str, indent: usize) -> Result<()> {
    let pad = "    ".repeat(indent);
    let domain_var = to_snake(domain);

    match stmt {
        Stmt::Let { name, value, .. } => {
            out.push_str(&format!("{pad}let {name} = "));
            lower_expr(out, value, &domain_var)?;
            out.push_str(";\n");
        }

        Stmt::Expr(expr) => {
            out.push_str(&pad);
            lower_expr(out, expr, &domain_var)?;
            out.push_str(";\n");
        }

        Stmt::Loop { body, .. } => {
            out.push_str(&format!("{pad}loop {{\n"));
            for s in body {
                lower_stmt(out, s, domain, indent + 1)?;
            }
            out.push_str(&format!("{pad}}}\n"));
        }

        Stmt::If { cond, then_body, else_body, .. } => {
            out.push_str(&format!("{pad}if "));
            lower_expr(out, cond, &domain_var)?;
            out.push_str(" {\n");
            for s in then_body {
                lower_stmt(out, s, domain, indent + 1)?;
            }
            if !else_body.is_empty() {
                out.push_str(&format!("{pad}}} else {{\n"));
                for s in else_body {
                    lower_stmt(out, s, domain, indent + 1)?;
                }
            }
            out.push_str(&format!("{pad}}}\n"));
        }

        Stmt::Return { value, .. } => {
            if let Some(val) = value {
                out.push_str(&format!("{pad}return "));
                lower_expr(out, val, &domain_var)?;
                out.push_str(";\n");
            } else {
                out.push_str(&format!("{pad}return;\n"));
            }
        }
    }

    Ok(())
}

fn lower_expr(out: &mut String, expr: &Expr, domain_var: &str) -> Result<()> {
    match expr {
        Expr::StringLit(s) => {
            out.push_str(&format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")));
        }
        Expr::IntLit(n) => out.push_str(&n.to_string()),
        Expr::FloatLit(f) => out.push_str(&format!("{:.6}", f)),
        Expr::BoolLit(b) => out.push_str(if *b { "true" } else { "false" }),
        Expr::DurationLit { nanos } => {
            if *nanos >= 1_000_000_000 && nanos % 1_000_000_000 == 0 {
                out.push_str(&format!("Duration::from_secs({})", nanos / 1_000_000_000));
            } else if *nanos >= 1_000_000 && nanos % 1_000_000 == 0 {
                out.push_str(&format!("Duration::from_millis({})", nanos / 1_000_000));
            } else if *nanos >= 1_000 && nanos % 1_000 == 0 {
                out.push_str(&format!("Duration::from_micros({})", nanos / 1_000));
            } else {
                out.push_str(&format!("Duration::from_nanos({})", nanos));
            }
        }
        Expr::Ident(name) => out.push_str(name),
        Expr::Field { object, field } => {
            lower_expr(out, object, domain_var)?;
            out.push_str(&format!(".{field}"));
        }

        Expr::MsiCall { module, method, args, .. } => {
            match (module.as_str(), method.as_str()) {
                ("event", "publish") => {
                    out.push_str(&format!("event_bus.emit({domain_var}.id(), "));
                    for (i, arg) in args.iter().enumerate() {
                        if i > 0 { out.push_str(", "); }
                        lower_expr(out, arg, domain_var)?;
                    }
                    out.push(')');
                }
                ("event", "wait") => {
                    out.push_str(&format!("event_bus.subscribe({domain_var}.id(), "));
                    if let Some(arg) = args.first() {
                        lower_expr(out, arg, domain_var)?;
                    }
                    out.push_str(").unwrap().wait(");
                    if let Some(arg) = args.get(1) {
                        lower_expr(out, arg, domain_var)?;
                    } else {
                        out.push_str("Duration::from_secs(1)");
                    }
                    out.push(')');
                }
                ("event", "subscribe") => {
                    out.push_str(&format!("event_bus.subscribe({domain_var}.id(), "));
                    if let Some(arg) = args.first() {
                        lower_expr(out, arg, domain_var)?;
                    }
                    out.push(')');
                }
                ("assoc", "put") => {
                    if args.len() >= 3 {
                        out.push_str("AssocStore::new(");
                        lower_expr(out, &args[0], domain_var)?;
                        out.push_str(").put(");
                        lower_expr(out, &args[1], domain_var)?;
                        out.push_str(", AssocValue::from_str(");
                        lower_expr(out, &args[2], domain_var)?;
                        out.push_str("))");
                    }
                }
                ("assoc", "get") => {
                    if args.len() >= 2 {
                        out.push_str("AssocStore::new(");
                        lower_expr(out, &args[0], domain_var)?;
                        out.push_str(").get(");
                        lower_expr(out, &args[1], domain_var)?;
                        out.push(')');
                    }
                }
                ("assoc", "query") => {
                    if args.len() >= 2 {
                        out.push_str("AssocStore::new(");
                        lower_expr(out, &args[0], domain_var)?;
                        out.push_str(").query(&AssocQuery::knn(");
                        lower_expr(out, &args[1], domain_var)?;
                        out.push_str("))");
                    }
                }
                ("assoc", "forget") => {
                    if args.len() >= 2 {
                        out.push_str("AssocStore::new(");
                        lower_expr(out, &args[0], domain_var)?;
                        out.push_str(").forget(");
                        lower_expr(out, &args[1], domain_var)?;
                        out.push(')');
                    }
                }
                _ => {
                    // Generic function call
                    if !module.is_empty() {
                        out.push_str(module);
                        out.push('.');
                    }
                    out.push_str(method);
                    out.push('(');
                    for (i, arg) in args.iter().enumerate() {
                        if i > 0 { out.push_str(", "); }
                        lower_expr(out, arg, domain_var)?;
                    }
                    out.push(')');
                }
            }
        }

        Expr::BinOp { op, left, right } => {
            out.push('(');
            lower_expr(out, left, domain_var)?;
            let op_str = match op {
                BinOp::Add => " + ",
                BinOp::Sub => " - ",
                BinOp::Mul => " * ",
                BinOp::Div => " / ",
                BinOp::Mod => " % ",
                BinOp::Eq => " == ",
                BinOp::Neq => " != ",
                BinOp::Lt => " < ",
                BinOp::Gt => " > ",
                BinOp::Lte => " <= ",
                BinOp::Gte => " >= ",
                BinOp::And => " && ",
                BinOp::Or => " || ",
            };
            out.push_str(op_str);
            lower_expr(out, right, domain_var)?;
            out.push(')');
        }

        Expr::UnaryOp { op, operand } => {
            match op {
                UnaryOp::Not => out.push('!'),
                UnaryOp::Neg => out.push('-'),
            }
            lower_expr(out, operand, domain_var)?;
        }
    }

    Ok(())
}

/// Convert PascalCase to snake_case for Rust variable names.
fn to_snake(name: &str) -> String {
    let mut result = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 { result.push('_'); }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    #[test]
    fn test_lower_simple_program() {
        let src = r#"
domain TestAgent {
    grant events "phone/"
    grant assoc "working" rw
    grant clock
    sealed
}

lane main in TestAgent {
    priority high
    energy balanced
    affinity big

    event.publish("agent/status", "ready")
}
"#;
        let tokens = Lexer::new(src).tokenize().unwrap();
        let program = Parser::new(tokens).parse().unwrap();
        let lowered = lower(&program).unwrap();

        assert!(lowered.rust_source.contains("substrate.domain(\"TestAgent\")"));
        assert!(lowered.rust_source.contains("Grant::Events(\"phone/\""));
        assert!(lowered.rust_source.contains(".seal()"));
        assert!(lowered.rust_source.contains("Priority::High"));
        assert!(lowered.rust_source.contains("event_bus.emit("));
        assert!(lowered.domains.contains(&"TestAgent".to_string()));
        assert!(lowered.lanes.contains(&"main".to_string()));
    }
}
